---
title: "My 2023 Attempts"
---

```{r setup, include=FALSE}
library(tidyverse)
library(tictoc)

knitr::opts_chunk$set()
xaringanExtra::use_panelset()

reticulate::use_virtualenv("./.venv")
```

```{python py-setup, include=FALSE}
import time
```


```{css, echo=FALSE}
.panel-tab {
  flex: 1 0 20%;
  text-align: center;
}

p {
  color: #cccccc;
}

p a {
  color: rgb(0, 153, 0);
}
p a:hover {
  color: #99ff99;
}
```

```{r, echo=FALSE}
part1 <- fs::dir_ls("./2022/", recurse = TRUE) %>%
  str_subset("_pt1") %>%
  str_extract(., "(?<=script_day)(.*)(?=_pt)") %>%
  as.numeric()

part2 <- fs::dir_ls("./2022/", recurse = TRUE) %>%
  str_subset("_pt2") %>%
  str_extract(., "(?<=script_day)(.*)(?=_pt)") %>%
  as.numeric()

one_done <- setdiff(setdiff(1:25, part2), setdiff(1:25, part1))
none_done <- intersect(setdiff(1:25, part2), setdiff(1:25, part1))

htmltools::tags$style(
  str_c(collapse = "\n",
    c(
      glue::glue(
        "#panelset_day-[one_done] {color: #EBB626 !important;}",
        .open = "[", .close = "]"
      ),
      glue::glue(
        "#panelset_day-[none_done] {color: #D63131 !important;}",
        .open = "[", .close = "]"
      )
    )
  )
)
```
